global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flowsentinel-engine"
    static_configs:
      - targets: ["flowsentinel-engine:8080"]
    metrics_path: /metrics

  - job_name: "flowsentinel-admin"
    static_configs:
      - targets: ["flowsentinel-admin:8001"]
    metrics_path: /metrics

